# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID

# This file contains the servo IDs for the robot's right arm and hand

r_shoulder_lift_joint:
  ID: 13

r_thumb_joint:
  ID: 31

r_index1_joint:
  ID: 34

r_middle1_joint:
  ID: 37

r_ring_joint:
  ID: 40

r_pinky_joint:
  ID: 44

l_thumb_joint:
  ID: 248

l_index1_joint:
  ID: 201

l_middle1_joint:
  ID: 250

l_ring_joint:
  ID: 252

l_pinky_joint:
  ID: 249
