---
- name: Add Key and repository for ROS
  become: true
  block:
    - name: Adding ROS key
      ansible.builtin.apt_key:
        url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
        state: present

    - name: Adding ROS repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu jammy main"
        state: present

- name: Install additional packages and ROS
  block:
    - name: Install basic build tools from apt
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - cmake
          - git
          - libyaml-cpp-dev
          - libbullet-dev
          - python3-colcon-common-extensions
          - python3-flake8
          - python3-pip
          - python3-pytest-cov
          - python3-rosdep
          - python3-setuptools
          - python3-vcstool
          # - python3-keras
          - python3-virtualenv
          - wget
        state: present
        update_cache: true
    
    - name: Install pip packages for keras
      ansible.builtin.pip:
        name:
          - keras
        virtualenv: /home/{{ ansible_env.USER }}/SOP-Robot/.venv

    - name: Install pip packages for testing into a virtualenv
      ansible.builtin.pip:
        name:
          - argcomplete
          - flake8-blind-except
          - flake8-builtins
          - flake8-class-newline
          - flake8-comprehensions
          - flake8-deprecated
          - flake8-docstrings
          - flake8-import-order
          - flake8-quotes
          - pytest-repeat
          - pytest-rerunfailures
          - pytest
        virtualenv: /home/{{ ansible_env.USER }}/SOP-Robot/.venv

    - name: Install FAST-RTPS and Cyclone DDS dependencies
      become: true
      ansible.builtin.apt:
        name:
          - libasio-dev
          - libtinyxml2-dev
          - libcunit1-dev
        state: present
        update_cache: true
        install_recommends: false

    - name: Install ROS2 iron and utility packages
      become: true
      ansible.builtin.apt:
        name:
          - ros-iron-desktop
          - ros-iron-dynamixel-sdk
          - ros-iron-dynamixel-workbench
          - ros-iron-ros2-control
          - ros-iron-ros2-controllers
          - ros-iron-control-toolbox
          - ros-iron-backward-ros
          - ros-iron-generate-parameter-library
          - ros-iron-kinematics-interface
          - ros-iron-kinematics-interface-kdl
          - ros-iron-ackermann-msgs
          - ros-iron-realtime-tools
          - ros-iron-joint-trajectory-controller
          - ros-iron-test-msgs
          - ros-iron-control-msgs
          - ros-iron-xacro
          - ros-iron-angles
          - v4l-utils
          - ros-iron-camera-calibration-parsers
          - espeak
        state: present
        update_cache: true

- name: Source ROS setup to bash
  block:
  - name: Source ROS setup for {{ ansible_env.USER }}
    ansible.builtin.lineinfile:
      path: /home/{{ ansible_env.USER }}/.bashrc
      line: source /opt/ros/iron/setup.bash
      state: present

  - name: Source ROS setup for noninteractive bash for {{ ansible_env.USER }}
    ansible.builtin.lineinfile:
      path: /home/{{ ansible_env.USER }}/.bashrc_noninteractive
      line: source /opt/ros/iron/setup.bash
      state: present
      create: true

- name: Install packages for SpeechRecognition
  block:
    - name: Install apt packages for SpeechRecognition
      become: true
      ansible.builtin.apt:
        name:
          - python3-pyaudio
        state: present
        update_cache: true

    - name: Install pip packages for SpeechRecognition
      ansible.builtin.pip:
        name:
          - opencv-python
          - dlib
          - TTS
          - simpleaudio
          - SpeechRecognition
          - farm-haystack
          - farm-haystack[inference]
        virtualenv: /home/{{ ansible_env.USER }}/SOP-Robot/.venv


- name: Download dynamixel and trigger udev
  block:
    - name: Download Dynamixel U2D2
      become: true
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ROBOTIS-GIT/dynamixel-workbench/master/99-dynamixel-workbench-cdc.rules
        dest: /etc/udev/rules.d/

    - name: Reload udev
      become: true
      ansible.builtin.command:
        cmd: udevadm control --reload-rules

    - name: Trigger udev
      become: true
      ansible.builtin.command:
        cmd: udevadm trigger

- name: Setup ROS
  block:
    - name: Initialize ROS
      become: true
      ansible.builtin.command:
      args:
        cmd: rosdep init
        creates: /etc/ros/rosdep/sources.list.d/20-default.list

    - name: Update ROS
      ansible.builtin.command:
        cmd: rosdep update
